sonar.organization=oneprofile

# must be unique in a given SonarQube instance
sonar.projectKey=oneprofile_nextjs

# this is the name and version displayed in the SonarQube UI. Was mandatory prior to SonarQube 6.1.
sonar.projectName=site-nextjs

# github repository
sonar.pullrequest.github.repository=oneprofile/site-nextjs

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set.
sonar.sources=\
    app/, \
    packages/

sonar.modules=\
    apps.site-nextjs, \
    domain.blog-model, \
    domain.blog-content-service, \
    packages.lib.logger, \
    packages.lib.markdown-library, \
    packages.spi.contentful-adapter, \
    packages.spi.notion-adapter, \
    packages.spi.redis-client, \
    packages.ui.react-library, \
    packages.ui.react-notion-library

apps.site-nextjs.sonar.projectBaseDir=apps/site-nextjs
apps.site-nextjs.sonar.sources=./components,./lib,./pages,./utils

domain.blog-model.sonar.projectBaseDir=packages/domain/model/blog-model
domain.blog-model.sonar.sources=./src

domain.blog-content-service.sonar.projectBaseDir=packages/domain/service/blog-content-service
domain.blog-content-service.sonar.sources=./src

packages.lib.logger.sonar.projectBaseDir=packages/lib/logger
packages.lib.logger.sonar.sources=./src

packages.lib.markdown-library.sonar.projectBaseDir=packages/lib/markdown-library
packages.lib.markdown-library.sonar.sources=./src

packages.spi.contentful-adapter.sonar.projectBaseDir=packages/spi/contentful-adapter
packages.spi.contentful-adapter.sonar.sources=./src

packages.spi.notion-adapter.sonar.projectBaseDir=packages/spi/notion-adapter
packages.spi.notion-adapter.sonar.sources=./src

packages.spi.redis-client.sonar.projectBaseDir=packages/spi/redis-client
packages.spi.redis-client.sonar.sources=./src

packages.ui.react-library.sonar.projectBaseDir=packages/ui/react-library
packages.ui.react-library.sonar.sources=./src

packages.ui.react-notion-library.sonar.projectBaseDir=packages/ui/react-notion-library
packages.ui.react-notion-library.sonar.sources=./src

# Long living branch of the project
sonar.branch.longLivedBranches.regex=(main)

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

#lcov report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=\
    **/__tests__/**,\
    **/*.tests.*,\
    **/stories/**,\
    **/__generated__/**,\
    **/__mocks__/**,\
    **/__fixtures__/**,\
    **/.eslintrc.js,\

sonar.coverage.exclusions=
    **/types/**,\
    **/types.ts,\
