name: CI on SPI

on:
  push:
    paths: [
      "packages/spi/**/*.ts",
      "packages/spi/**/package.json",
    ]
    branches: [ main ]
  pull_request:
    paths: [
      "packages/spi/**/*.ts",
      "packages/spi/**/package.json",
    ]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "7.x"

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint check
        run: pnpm turbo run lint --filter contentful-adapter --filter notion-adapter

      - name: Run the tests and generate coverage report
        run: pnpm turbo run test --filter contentful-adapter --filter notion-adapter

      - name: Build
        run: pnpm turbo run build --filter contentful-adapter --filter notion-adapter

